name: flutter_dio_queue
description: A robust request queue layer on top of Dio.

repository: https://github.com/mhmd435/dio_queue
homepage: https://github.com/mhmd435/dio_queue
issue_tracker: https://github.com/mhmd435/dio_queue/issues

version: 0.1.3
# publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  connectivity_plus: ^6.1.5
  hive: ^2.2.3
  meta: ^1.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_test: ^1.0.0
  hive_flutter: ^1.1.0

flutter:
  uses-material-design: false
